
package com.redxun.serviceEngineering.core.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IXcmgPeieWebserviceService", targetNamespace = "http://peie.webservice.waji.xcmg.kmss.landray.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IXcmgPeieWebserviceService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "data", targetNamespace = "http://peie.webservice.waji.xcmg.kmss.landray.com/", className = "com.webservice.oa2.Data")
    @ResponseWrapper(localName = "dataResponse", targetNamespace = "http://peie.webservice.waji.xcmg.kmss.landray.com/", className = "com.webservice.oa2.DataResponse")
    public String data();

}
