
package com.redxun.serviceEngineering.core.webservice;

import com.redxun.sys.core.util.SysPropertiesUtil;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "XcmgPeieWebserviceServiceService", targetNamespace = "http://peie.webservice.waji.xcmg.kmss.landray.com/", wsdlLocation = "http://10.188.0.145/sys/webservice/xcmgPeieWebserviceService?wsdl")
public class XcmgPeieWebserviceServiceService
        extends Service {

    private final static URL XCMGPEIEWEBSERVICESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException XCMGPEIEWEBSERVICESERVICESERVICE_EXCEPTION;
    private final static QName XCMGPEIEWEBSERVICESERVICESERVICE_QNAME = new QName("http://peie.webservice.waji.xcmg.kmss.landray.com/", "XcmgPeieWebserviceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String oAxcmgPeieWebserviceService = SysPropertiesUtil.getGlobalProperty("OAxcmgPeieWebserviceService");
            url = new URL("http://10.188.0.145/sys/webservice/xcmgPeieWebserviceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XCMGPEIEWEBSERVICESERVICESERVICE_WSDL_LOCATION = url;
        XCMGPEIEWEBSERVICESERVICESERVICE_EXCEPTION = e;
    }

    public XcmgPeieWebserviceServiceService() {
        super(__getWsdlLocation(), XCMGPEIEWEBSERVICESERVICESERVICE_QNAME);
    }

    public XcmgPeieWebserviceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XCMGPEIEWEBSERVICESERVICESERVICE_QNAME, features);
    }

    public XcmgPeieWebserviceServiceService(URL wsdlLocation) {
        super(wsdlLocation, XCMGPEIEWEBSERVICESERVICESERVICE_QNAME);
    }

    public XcmgPeieWebserviceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XCMGPEIEWEBSERVICESERVICESERVICE_QNAME, features);
    }

    public XcmgPeieWebserviceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XcmgPeieWebserviceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns IXcmgPeieWebserviceService
     */
    @WebEndpoint(name = "XcmgPeieWebserviceServicePort")
    public IXcmgPeieWebserviceService getXcmgPeieWebserviceServicePort() {
        return super.getPort(new QName("http://peie.webservice.waji.xcmg.kmss.landray.com/", "XcmgPeieWebserviceServicePort"), IXcmgPeieWebserviceService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IXcmgPeieWebserviceService
     */
    @WebEndpoint(name = "XcmgPeieWebserviceServicePort")
    public IXcmgPeieWebserviceService getXcmgPeieWebserviceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://peie.webservice.waji.xcmg.kmss.landray.com/", "XcmgPeieWebserviceServicePort"), IXcmgPeieWebserviceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XCMGPEIEWEBSERVICESERVICESERVICE_EXCEPTION != null) {
            throw XCMGPEIEWEBSERVICESERVICESERVICE_EXCEPTION;
        }
        return XCMGPEIEWEBSERVICESERVICESERVICE_WSDL_LOCATION;
    }

}
